{"name": "Creation User Clone Error", "status": "passed", "start": 1732664537687, "stop": 1732664538468, "uuid": "7cb5dfb1-393d-460c-880e-52ed7a5c7f54", "historyId": "06bfc9d0d8d5580f896a5a2211097735", "testCaseId": "06bfc9d0d8d5580f896a5a2211097735", "fullName": "tests.test_create_user.TestCreateUser#test_create_user_clone_error", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_create_user"}, {"name": "subSuite", "value": "TestCreateUser"}, {"name": "host", "value": "DESKTOP-V6N82FL"}, {"name": "thread", "value": "24496-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_create_user"}]}